### PR TITLE
Fixing inconsistent version number and bumping to 3.0.3

### PR DESCRIPTION
**Pull request by KMojek**
Addresses https://github.com/TechSmith/CamtasiaWin/issues/6592

### CODE REVIEW

**Comment by BingTSC** [comment]
>  Fixing inconsistent version number and bumping to 3.0.3

where and where are inconsistent?

**Comment by KMojek** [comment]
PROJECT_version_point wasn't updated from 1 to 2, so the dll was marked as version 3.0.1 instead of 3.0.2

**Comment by KMojek** [comment]
https://content.screencast.com/users/kmojek/folders/Snagit/media/3b7beba6-9412-4f46-85d5-d30f4b728ea5/04.11.2017-10.02.png

**Comment by qunliu** [comment]
Looks good to me 👍 It would be good to have Bethany also look at it so we don't miss anything.

**Comment by bberton** [comment]
I think it looks ok 👍 

This is what I checked:

Compared it to a past commit with a known good version rev:
https://github.com/TechSmith/mp4v2/pull/3/commits/d10bdd962bd865fcf881aa41f0710ff99e871e19

Verified that the rc file actually uses the defines we changed:
https://github.com/TechSmith/mp4v2/blob/master/mp4v2-Win/libmp4v2/Version.rc#L4-L41

Looked at the dlls in Windows explorer & made sure the Product Version & File Versions were both updated:
image

Built a local NuGet package off of this branch, compared that package to the package on the NuGet share:
image

**Pull request merged**
