### PR TITLE
Fix crash in mp4 get track media data name

### PR DESCRIPTION
**Pull request by dchengTSC**
Was able to get a crash before with this particular file, which was generated by a fuzzer. With this fix, it no longer crashes.

https://user-images.githubusercontent.com/2083945/111637536-e54de700-87cf-11eb-8522-87d2864a22c8.mp4

### CODE REVIEW

**Review by altonlea — APPROVED** [review]
I don't know what the runner is for.  The fix makes sense though.  Why does no-one ever check pointers before using them?  Code defensively...that's my motto.  Expect failure until proven otherwise!

**Review by KMojek — CHANGES_REQUESTED** [review]
Code looks good but I think we need to keep this at VS 2017 because it is consumed by TREC which is in turn consumed by GoTREC... which needs to be at VS 2017 because it's part of RecordingLibraries. 😞

**Comment by dchengTSC** [comment]
Ok, done!

**Review by KMojek — APPROVED** [review]
👍

**Pull request merged**
