### PR TITLE
Upgrade to VS2017

### PR DESCRIPTION
**Pull request by ajorians**
## Introduction

Updated this to VS2017 part of this card: https://github.com/TechSmith/CamtasiaWin/issues/9202

## Testing Notes

I build this project in all configuration permutations:
image

And make a NuPkg file:
image

Hope that helps! :smiley:

### CODE REVIEW

**Comment by sgarske** [comment]
do you need to update https://github.com/TechSmith/mp4v2/blob/master/mp4v2-Win/libmp4v2/Version.rc ?  I just saw that had a change from the VS2015 upgrade

**Comment by sgarske** [comment]
Are we supposed to document modifications to this repo somewhere due to the license?  Does this count?  @dchengTSC ?

**Comment by dchengTSC** [comment]
I believe since it's a public TechSmith repo that we are OK. We've certainly made changes in the past without doing anything extra.

**Comment by ajorians** [comment]
> do you need to update https://github.com/TechSmith/mp4v2/blob/master/mp4v2-Win/libmp4v2/Version.rc ? I just saw that had a change from the VS2015 upgrade

Hey @sgarske , yes I did.  The actual values are in a header file:
image

I looked to make sure these values in the header file aren't going to cause issues and to the best of my knowledge they won't.  Hope that helps! :smiley:

**Comment by sgarske** [comment]
:+1:

**Pull request merged**
